name: Deploy docs

on:
  push:
      branches:
        - main
jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Chekout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js 
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Build Docs
        run: |
          npm run docs:build
          if [ $? -eq 0 ]; then
            echo "Build succeeded!"
          else
            echo "Build failed! -ㅡ-"
            exit 1
          fi
      - name: Reload Nginx
        run: brew services reload nginx