name: Build Docs

on:
  push:
      branches:
        - main
jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Chekout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js 
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Build Docs
        run: npm run docs:build
